-- NEXUS initial Supabase/Postgres schema migration
-- Mirrors current Nexus schema while switching vector storage to pgvector.

create extension if not exists vector;

create table if not exists knowledge (
  id text primary key,
  module text not null check (module in ('people', 'projects', 'notes', 'external')),
  entity_links text not null,
  tags text not null,
  source text not null,
  created_at text not null,
  updated_at text not null,
  embedding vector(768),
  raw_text text not null,
  structured_data text not null
);

create table if not exists conversations (
  id integer generated by default as identity primary key,
  name text not null default 'New Chat',
  created_at timestamp with time zone default current_timestamp,
  updated_at timestamp with time zone default current_timestamp,
  messages text not null default '[]'
);

create table if not exists modes (
  id integer generated by default as identity primary key,
  name text not null,
  trigger_phrase text,
  instruction text not null,
  created_at timestamp with time zone default current_timestamp
);

create index if not exists knowledge_embedding_ivfflat_idx
  on knowledge
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create index if not exists conversations_fts_idx
  on conversations
  using gin (to_tsvector('english', coalesce(name, '') || ' ' || coalesce(messages, '')));

create or replace function search_knowledge_by_embedding(
  query_embedding vector(768),
  match_count integer default 5
)
returns table (
  id text,
  module text,
  tags text,
  raw_text text,
  structured_data text,
  distance double precision
)
language sql
stable
as $$
  select
    k.id,
    k.module,
    k.tags,
    k.raw_text,
    k.structured_data,
    (k.embedding <=> query_embedding) as distance
  from knowledge k
  where k.embedding is not null
  order by k.embedding <=> query_embedding
  limit match_count;
$$;

create or replace function find_most_similar_knowledge(
  query_embedding vector(768)
)
returns table (
  id text,
  module text,
  tags text,
  raw_text text,
  structured_data text,
  distance double precision
)
language sql
stable
as $$
  select
    k.id,
    k.module,
    k.tags,
    k.raw_text,
    k.structured_data,
    (k.embedding <=> query_embedding) as distance
  from knowledge k
  where k.embedding is not null
  order by k.embedding <=> query_embedding
  limit 1;
$$;
