-- NEXUS folders: organizational grouping for chat threads
-- Single-user system: user_id nullable for future extensibility

create table if not exists folders (
  id integer generated by default as identity primary key,
  name text not null,
  created_at timestamp with time zone default current_timestamp,
  user_id text
);

alter table conversations add column if not exists folder_id integer references folders(id) on delete set null;

create index if not exists conversations_folder_id_idx on conversations(folder_id);
