-- Knowledge tab folder tree: separate from chat folders (folders table).
-- Trash is is_trashed flag; nesting capped at 6 levels.

create table if not exists knowledge_folders (
  id integer generated by default as identity primary key,
  name text not null,
  parent_id integer references knowledge_folders(id) on delete cascade,
  depth integer not null check (depth <= 6),
  position integer not null,
  is_trashed boolean not null default false,
  created_at timestamp with time zone default current_timestamp,
  updated_at timestamp with time zone default current_timestamp
);

create index if not exists knowledge_folders_parent_id_idx on knowledge_folders(parent_id);
create index if not exists knowledge_folders_is_trashed_idx on knowledge_folders(is_trashed);
create index if not exists knowledge_folders_parent_position_idx on knowledge_folders(parent_id, position);

-- Soft-delete folder and all descendants in one transaction
create or replace function trash_knowledge_folder_and_descendants(target_id integer)
returns void
language plpgsql
security definer
as $$
begin
  with recursive descendants as (
    select id from knowledge_folders where id = target_id
    union all
    select kf.id from knowledge_folders kf
    join descendants d on kf.parent_id = d.id
  )
  update knowledge_folders
  set is_trashed = true, updated_at = current_timestamp
  where id in (select id from descendants);
end;
$$;
